runtime: java21
instance_class: F2

env_variables:
  DB_HOST: "ge4q7.h.filess.io"
  DB_PORT: "61000"
  DB_NAME: "gastrostockdb_bicyclebuy"
  DB_USER: "gastrostockdb_bicyclebuy"
  DB_PASSWORD: "c36831a47c4e284e65c462ddfbdff2d0a57b43b8"

handlers:
  - url: /static
    static_dir: frontend/build/static

  - url: /api/.*
    script: auto

  - url: /.*
    static_files: frontend/build/index.html
    upload: frontend/build/index.html

  - url: /(.*\.(gif|png|jpg|jpeg|svg|webp))
    static_files: frontend/public/\1
    upload: frontend/public/(.*\.(gif|png|jpg|jpeg|svg|webp))
