runtime: java21
instance_class: F2

env_variables:
  DB_HOST: "ge4q7.h.filess.io"
  DB_PORT: "61000"
  DB_NAME: "gastrostockdb_bicyclebuy"
  DB_USER: "gastrostockdb_bicyclebuy"
  DB_PASSWORD: "c36831a47c4e284e65c462ddfbdff2d0a57b43b8"

handlers:
  - url: /static
    static_dir: /static

  - url: /.* 
    script: auto