import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('button', { name: 'Registrarse' }).click();
  await page.getByRole('textbox', { name: 'Nombre del dueno' }).click();
  await page.getByRole('textbox', { name: 'Nombre del dueno' }).fill('Alberto');
  await page.getByRole('textbox', { name: 'Nombre del dueno' }).press('Tab');
  await page.getByRole('textbox', { name: 'Apellidos del dueno' }).fill('Munoz');
  await page.getByRole('textbox', { name: 'Apellidos del dueno' }).press('Tab');
  await page.getByRole('textbox', { name: 'Correo Electrónico' }).fill('albermun@ejemplo.com');
  await page.getByRole('textbox', { name: 'Correo Electrónico' }).press('Tab');
  await page.getByRole('textbox', { name: 'Teléfono' }).fill('678987495');
  await page.getByRole('textbox', { name: 'Teléfono' }).press('Tab');
  await page.getByRole('textbox', { name: 'Usuario' }).fill('almun1');
  await page.getByRole('textbox', { name: 'Usuario' }).press('Tab');
  await page.getByRole('textbox', { name: 'Contrasena', exact: true }).fill('almun');
  await page.getByRole('textbox', { name: 'Contrasena', exact: true }).click();
  await page.getByRole('textbox', { name: 'Contrasena', exact: true }).fill('almunMun1234565J.');
  await page.getByRole('textbox', { name: 'Confirmar Contrasena' }).click();
  await page.getByRole('textbox', { name: 'Confirmar Contrasena' }).fill('almunMun1234565J.');
  await page.getByRole('button', { name: 'Registrarse' }).click();
  await page.getByRole('heading', { name: 'Inicia en tu negocio' }).click();
  await page.getByRole('button', { name: 'Registrar negocio' }).click();
  await page.getByRole('textbox', { name: 'Nombre del negocio' }).click();
  await page.getByRole('textbox', { name: 'Nombre del negocio' }).fill('Negocio Nuevo');
  await page.getByRole('textbox', { name: 'Nombre del negocio' }).press('Tab');
  await page.getByRole('textbox', { name: 'Token de negocio' }).fill('98321');
  await page.getByRole('textbox', { name: 'Dirección' }).click();
  await page.getByRole('textbox', { name: 'Dirección' }).fill('Nueva Calle');
  await page.getByRole('textbox', { name: 'Dirección' }).press('Tab');
  await page.getByRole('textbox', { name: 'Código Postal' }).fill('41007');
  await page.getByRole('textbox', { name: 'Código Postal' }).press('Tab');
  await page.getByRole('textbox', { name: 'Ciudad' }).fill('Sevilla');
  await page.getByRole('textbox', { name: 'Ciudad' }).press('Tab');
  await page.getByRole('textbox', { name: 'País' }).fill('España');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Registrar negocio', exact: true }).click();
  await page.getByRole('button', { name: 'Ver' }).click();
  await page.getByRole('button', { name: 'Ver' }).click();
  await page.getByRole('button', { name: 'empleados Empleados' }).click();
  await page.getByRole('button', { name: '⬅ Volver' }).click();
  await page.getByRole('button', { name: 'dashboard Dashboard' }).click();
  await page.getByRole('heading', { name: 'DashBoard' }).click();
  await page.getByRole('button', { name: '⬅ Volver' }).click();
  await page.getByRole('button', { name: 'inventario Inventario' }).click();
  await page.getByRole('heading', { name: 'Inventario' }).click();
  await page.getByRole('button', { name: '⬅ Volver' }).click();
  await page.getByRole('button', { name: 'ventas Ventas' }).click();
  await page.getByRole('heading', { name: '📜 Historial de Pedidos' }).click();
  await page.getByRole('button', { name: '⬅ Volver' }).click();
  await page.getByRole('button', { name: 'proveedores Proveedores' }).click();
  await page.getByRole('heading', { name: 'Proveedores' }).click();
  await page.getByRole('button', { name: '⬅ Volver' }).click();
  await page.getByRole('button', { name: 'carta Carta' }).click();
});