name: Automatic Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create ZIP
        run: zip -r release.zip .

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }} #Modificar si queremos modificar la version, ahora mismo seria 1.0.X
          release_name: "v1.0.${{ github.run_number }}" #Modificar si queremos modificar la version, ahora mismo seria 1.0.X
#Cambiar por el mensaje que se desee si quieres proporcinar mas informacion sobre la nueva release
          body: "Nueva Release."  
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release.zip
          asset_name: source_code_v1.0.${{ github.run_number }}.zip
          asset_content_type: application/zip