name: release-please

on:
  push:
    branches:
      - main
      - feat/47

permissions:
  contents: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Release Please
        id: release_please
        uses: googleapis/release-please-action@v4
        with:
          release-type: maven
          target-branch: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create ZIP
        if: steps.release_please.outputs.release_created == 'true'
        run: zip -r release.zip .

      - name: Upload Release Asset
        if: steps.release_please.outputs.release_created == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_please.outputs.upload_url }}
          asset_path: release.zip
          asset_name: source_code_v${{ steps.release_please.outputs.tag_name }}.zip
          asset_content_type: application/zip